model:
  output_dir: checkpoints
  name: 
  pretrained: true
  device: cuda
  push_to_hub: False
  dims: [32, 64, 128, 256]
  num_heads: [4, 4, 8, 8]
  num_classes: 1

training:
  seed: 666
  num_epochs: 100
  mixed_precision: no
  gradient_accumulation_steps: 1
  early_stopping_patience: 3
  min_epochs_before_stop: 50
  save_every_n_epochs: 10
  log_every_n_steps: 50
  val_every_n_epochs: 10
  loss_alpha: 0.5
  optimizer: adamw
  base_lr: 1e-3
  weight_decay: 1e-2
  momentum: # SGD
  scheduler: onecycle
  # cosine_restart
  T_0: 10
  T_mult: 1
  eta_min: 1e-6
  # onecycle
  max_lr: 1e-3
  pct_start: 0.3
  anneal_strategy: cos
  # plateau
  plateau_factor: 0.5
  plateau_patience: 5
  min_lr: 1e-6

dataset:
  root_path: /home/swjtu/workspace_01/data/crack_segmentation_dataset
  batch_size: 32
  size: [448, 448]
